swagger: '2.0'
info:
  version: '0.0.1'
  title: 'Behandlungsjournal'
  description: 'Ein Behandlungsjournal für kranke Tiere'
  license:
    name: 'MIT'
host: localhost
schemes:
  - 'http'
basePath: '/api'
consumes:
  - application/json
produces:
  - application/json
paths:
 /users:
   get:
     operationId: 'getAllUsers'
     description: 'Returns all users'
     produces:
        - application/json
     tags:
        - 'user'
     responses:
      "200":
       description: 'A list of all users.'
       schema:
        type: 'array'
        items:
         $ref: '#/definitions/User'
      default:
       description: 'Unexpected error'
       schema:
         $ref: '#/definitions/Error'
 /user/{name}:
    get:
     operationId: 'getUserbyID'
     description: 'Returns user by ID (ObjectID)'
     produces:
        - "application/json"
     parameters:
       - name: name
         in: path
         required: true
         type: string
         description: "Mongodb [ObjectID](https://docs.mongodb.com/v3.2/reference/method/ObjectId/)"
     tags:
        - "user"
     responses:
      "200":
       description: 'Returns user by ID'
       schema:
        type: 'array'
        items:
         $ref: '#/definitions/User'
      default:
       description: 'Unexpected error'
       schema:
        $ref: '#/definitions/Error'

definitions:
  User:
    type: "object"
    properties:
        _id:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
        password:
          type: "string"
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
