version: '2'
services:

  web:
    image: node:6.10
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm i @angular/cli@1.0.0-rc.2 -g; npm i gulp -g; gulp sass; gulp build_server; ng build; npm run loaddemodata; node dist/server.js;'
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/test"

  mongo:
    image: mongo:3
    command: mongod
    networks:
      - all

networks:
  all:
